applications:
  - args:
      llm_configs:
        - model_loading_config:
          - ./configs/model_config/llama_3dot2_1B_no_accelerator.yaml
    import_path: ray.serve.llm:build_openai_app
    name: llm-endpoint
    route_prefix: /
